name: Build YAML matrix from changed files and/or full scan
description: Emits files_json + count for YAML files to process
inputs:
  changed_file_list:
    description: File that lists changed paths (one per line)
    required: true
  path:
    description: Root path to consider (e.g., aws / gcp / azure)
    required: true
outputs:
  files_json:
    description: JSON array of YAML files to process
    value: ${{ steps.matrix.outputs.files_json }}
  count:
    description: Count of YAML files to process
    value: ${{ steps.matrix.outputs.count }}
  matrix_json:
    description: JSON array of objects {file, account_id}
    value: ${{ steps.enrich.outputs.matrix_json }}
  matrix_count:
    description: Count of items in matrix_json
    value: ${{ steps.enrich.outputs.matrix_count }}
runs:
  using: composite
  steps:
    - id: matrix
      shell: bash
      run: |
        set -euo pipefail

        ROOT="${{ inputs.path }}"
        CHANGED_FILE="${{ inputs.changed_file_list }}"

        echo "Scanning for changes under ${ROOT}/"
        echo "Using changed list file: ${CHANGED_FILE}"

        # Ensure the changed list exists (empty if not present)
        if [ ! -f "$CHANGED_FILE" ]; then
          echo "Changed file list not found; creating empty file."
          : > "$CHANGED_FILE"
        fi

        # If any .tf changed under ROOT => include ALL YAML under ROOT
        if grep -Eq "^${ROOT}/.*\.tf$" "$CHANGED_FILE"; then
          echo "Terraform change detected -> include ALL YAML under ${ROOT}/"
          src=$(find "${ROOT}" -type f \( -name '*.yaml' -o -name '*.yml' \) -print | sort || true)
        else
          echo "No Terraform change -> include only CHANGED YAML under ${ROOT}/"
          # IMPORTANT: keep stderr redirection to /dev/null (do NOT rewrite to ${ROOT}/null)
          src=$(grep -E "^${ROOT}/.*\.(ya?ml)$" "$CHANGED_FILE" 2>/dev/null || true)
        fi

        # Convert to JSON
        files_json=$(
          printf '%s\n' "$src" \
          | jq -R -s -c 'split("\n") | map(select(length>0))'
        )

        # Filter to files that still exist at HEAD (avoid deleted ones)
        files_json=$(
          jq -r '.[]' <<<"$files_json" \
          | while read -r f; do
              [ -f "$f" ] && echo "$f"
            done \
          | jq -R -s -c 'split("\n") | map(select(length>0))'
        )

        {
          echo "files_json<<EOF"
          echo "$files_json"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        count=$(jq -r 'length' <<<"$files_json")
        echo "count=${count}" >> "$GITHUB_OUTPUT"
        echo "Matrix will run for ${count} file(s)."

    - name: Build {file, account_id} matrix
      shell: bash
      id: enrich
      run: |
        set -euo pipefail
        files_json='${{ steps.prepare.outputs.files_json }}'
        pair_json=$(
          jq -r '.[]' <<<"$files_json" \
          | while read -r f; do
              [ -f "$f" ] || continue
              acc=$(yq -r '.account_id // empty' "$f" || true)
              [ -n "$acc" ] && printf '{"file":%s,"account_id":%s}\n' "$(jq -R <<<"$f")" "$(jq -R <<<"$acc")"
            done | jq -s -c '.'
        )
        [ -z "${pair_json:-}" ] && pair_json='[]'
        { echo "matrix_json<<EOF"; echo "$pair_json"; echo "EOF"; } >> "$GITHUB_OUTPUT"
        echo "matrix_count=$(jq -r 'length' <<<"$pair_json")" >> "$GITHUB_OUTPUT"
