name: Build YAML matrix from changed files and/or full scan
description: Emits files_json + count for YAML files to process
inputs:
  changed_file_list:
    description: File that lists changed paths (one per line)
    required: true
  path:
    description: Root path to consider (e.g., aws)
    required: true
outputs:
  files_json:
    description: JSON array of YAML files to process
    value: ${{ steps.matrix.outputs.files_json }}
  count:
    description: Count of YAML files to process
    value: ${{ steps.matrix.outputs.count }}
runs:
  using: composite
  steps:
    - id: matrix
      shell: bash
      run: |
        set -euo pipefail

          if grep -Eq '^aws/.*\.tf$' changed.txt; then
            echo "Terraform change detected -> include ALL YAML under aws/"
            files_json=$(
              find aws -type f \( -name '*.yaml' -o -name '*.yml' \) -print \
              | jq -R -s -c 'split("\n") | map(select(length>0))'
            )
          else
            echo "No Terraform change -> include only CHANGED YAML under aws/"
            files_json=$(
              grep -E '^aws/.*\.(ya?ml)$' changed.txt 2>/aws/null \
              | jq -R -s -c 'split("\n") | map(select(length>0))'
            )
          fi

          # Fallback to [] if empty
          [ -z "${files_json:-}" ] && files_json='[]'

          {
            echo "files_json<<EOF"
            echo "$files_json"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          echo "count=$(jq -r 'length' <<<"$files_json")" >> "$GITHUB_OUTPUT"
          echo "Matrix will run for $(jq -r 'length' <<<"$files_json") file(s)."