# This is a basic workflow to help you get started with Actions

name: Test Python

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      namespace:
        required: true
        type: string
        default: test-abc
        
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Setup pytest
      - name: Pytest
        run: |
          # python -m pip install --upgrade pip
          # pip install pytest pytest-html
          # pytest --version
          # echo "${{ startsWith('${{ github.event.inputs.namespace }}', 'test') }}"
          # echo "${{ github.event.inputs.namespace }}"
          # echo "Result: ${{ startsWith(github.event.inputs.namespace, 'test') }}"
          # echo $Result
          # if [ startsWith(github.event.inputs.namespace, 'test') ]; then
          #   echo "If condition..."
          # else
          #   echo "Else condition..."
          # fi
          NAMESPACE="${{ github.event.inputs.namespace }}"  # Assign GitHub variable to shell variable
          if [ "$NAMESPACE" == test* ]; then
            echo "Namespace starts with 'test'"
          else
            echo "Namespace does NOT start with 'test'"
          fi
          

