name: Main Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          if ["a" == "a"]; then
            echo "PR_NUMBER=if_condition"
          else
            echo "PR_NUMBER=else_condition"
          # ...
          # echo "PR_NUMBER=abctest" >> $GITHUB_OUTPUT
          echo "::set-output name=PR_NUMBER::${{ env.PR_NUMBER }}"

  publish:
    needs: [job1]
    uses: mayankagarwal19911/to_del/.github/workflows/re-usable-workflow.yaml@main
    with:
      my_var: ${{ needs.job1.outputs.pr-number }}


