name: Main Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.set-output.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          if [ "a" == "a" ]; then
            echo "PR_NUMBER=if_condition" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=else_condition" >> $GITHUB_ENV
          fi
      - name: Set output
        id: set-output
        run: echo "PR_NUMBER=abctest" >> $GITHUB_OUTPUT
        # echo "::set-output name=pr-number::${{ env.PR_NUMBER }}"
        # ...
        # echo "PR_NUMBER=abctest" >> $GITHUB_OUTPUT
        # echo "PR_NUMBER=$(echo ${{ env.PR_NUMBER }})" >> $GITHUB_OUTPUT

  publish:
    needs: [job1]
    uses: mayankagarwal19911/to_del/.github/workflows/re-usable-workflow.yaml@main
    with:
      my_var: ${{ needs.job1.outputs.pr-number }}


