name: Main Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          # ...
          echo "PR_NUMBER=1234567" >> $GITHUB_OUTPUT

  publish:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{ needs.job1.outputs.pr-number }}

    # uses: mayankagarwal19911/to_del/.github/workflows/re-usable-workflow.yaml@main
    # with:
    #   my_var: ${{ needs.job1.outputs.pr-number }}
