name: Reusable Workflow

on:
  workflow_call:
    inputs:
      my_var:
        required: true
        type: string

jobs:
  read-env-var:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variable
      run: echo "The value of my_var is:${{ github.event.inputs.my_var }}"
