name: Test envsubst

on: workflow_dispatch

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Taggig
        run: |
          echo "imageTag=${{ github.run_number }}" >> $GITHUB_ENV
          
      - name: Render k8s manifests
        env:
          imageTag: ${{ env.imageTag }}
        run: |-
          envsubst < test/deployment.yaml > rendered_deployment.yaml
          cat rendered_deployment.yaml
        
