name: Proxy Workflow

on:
  workflow_dispatch:
    inputs:
      create_proxy:
        description: 'Create Proxy'
        required: true
        default: 'false'
      deploy_proxy:
        description: 'Deploy Proxy'
        required: true
        default: 'false'
      delete_undeploy_api_proxy:
        description: 'Delete & Undeploy Proxy'
        required: true
        default: 'false'

run-name: >-
  ${{ 
    inputs.create_proxy == 'true' && inputs.deploy_proxy == 'true' && inputs.delete_undeploy_api_proxy == 'true' && 'Create Proxy + Deploy Proxy + Delete and Undeploy Proxy' ||
    inputs.create_proxy == 'true' && inputs.deploy_proxy == 'true' && 'Create Proxy + Deploy Proxy' ||
    inputs.create_proxy == 'true' && inputs.delete_undeploy_api_proxy == 'true' && 'Create Proxy + Delete and Undeploy Proxy' ||
    inputs.deploy_proxy == 'true' && inputs.delete_undeploy_api_proxy == 'true' && 'Deploy Proxy + Delete and Undeploy Proxy' ||
    inputs.create_proxy == 'true' && 'Create Proxy' ||
    inputs.deploy_proxy == 'true' && 'Deploy Proxy' ||
    inputs.delete_undeploy_api_proxy == 'true' && 'Delete and Undeploy Proxy'
  }}

jobs:
  show-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "create_proxy = ${{ inputs.create_proxy }}"
          echo "deploy_proxy = ${{ inputs.deploy_proxy }}"
          echo "delete_undeploy_api_proxy = ${{ inputs.delete_undeploy_api_proxy }}"
