name: Test envsubst For SQL

on: workflow_dispatch

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Render DB Name
        env:
          DB_NAME: TEST-0123
        run: |-
          envsubst < test/test_param_sql.sql > rendered_test_param_sql.sql
          cat rendered_test_param_sql.sql
        
