on: workflow_dispatch

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Merge DNS Names in YAML file using yq
        run: |
          # Merge lists from dnsname and dnsname2 and save it to a new file
          yq e -i '.dnsname = (.dnsname + .dnsname2) | del(.dnsname2)' ${GITHUB_WORKSPACE}/example.yaml > ${GITHUB_WORKSPACE}/example_2.yaml

      - name: Display updated YAML file
        run: cat ${GITHUB_WORKSPACE}/example_2.yaml
