name: Test OIDC

on:
  workflow_dispatch:
  
jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/1073411163963/locations/global/workloadIdentityPools/github-action-pool/providers/github'
          service_account: 'github-action-sa@xergyinc-1493409480060.iam.gserviceaccount.com'
          
  install-gcloud:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud iam service-accounts list --project=XergyInc'
